### ISSUE TITLE
No reads pass filter in dada2

### ISSUE THREAD

**Issue by science-chump** [ErnakovichLab/dada2_ernakovichlab#4]
I recently got a new batch of 16S samples and as I tried running them through the dada2 pipeline, about half of the samples are losing all reads while the other half is losing 95% of the reads. I have changed some of the parameter settings on dada2 including the truncation length, maxEE and maxN with no success.

I have also ran these same reads through qiime which seem to yield expected results. Not sure what is going on but here is a link to what appears to be a similar issue to the one I am running into.

https://github.com/benjjneb/dada2/issues/618

**Comment by hhollandmoritz** [comment]
@srs1085 Can you post the file path on premise to the files that are losing their reads? Also if you have the pre-filtering quality score images, and can attach them here, that would be helpful too. :)

Thanks!

**Comment by science-chump** [comment]
![fwd_qual_plots](https://user-images.githubusercontent.com/61884350/148071027-d64a39c2-1cdc-4aab-a919-4680a4a91eb5.png)
![rev_qual_plots](https://user-images.githubusercontent.com/61884350/148071030-3e77bbd7-cc26-42c8-b5af-aa0cf78a3689.png)
```

/mnt/home/ernakovich/srs1085/DATA/Betula_reads/16S/02_filter/preprocessed_R
/mnt/home/ernakovich/srs1085/DATA/Betula_reads/16S/02_filter/preprocessed_F
```

**Comment by hhollandmoritz** [comment]
@science-chump 
Is this the code you used to filter the data? 
> filt_out <- filterAndTrim(fwd=file.path(subF.fp, fastqFs), filt=file.path(filtpathF, fastqFs),
                          rev=file.path(subR.fp, fastqRs), filt.rev=file.path(filtpathR, fastqRs),
                          truncLen=c(230,220), maxEE=c(3,2), truncQ=2, maxN=0, rm.phix=TRUE,
                          compress=TRUE, verbose=TRUE, multithread=TRUE)

I think perhaps your maxEE scores might be too stringent,  try making both 2 and see if that helps.

**Comment by science-chump** [comment]
I did a number of variations with the max EE and truncLen and neither seemed to do much.

**Comment by science-chump** [comment]
Okay, so I was being too restrictive when I was making these amendments. I kicked the max EE to (5,5) and the truncLen to (230,230) and now a ton of reads are getting through.

**Comment by hhollandmoritz** [comment]
EE set to (5,5) is higher than I think is reasonable. :( If you lower it back down to (2,2) but have the length set to (230,230) does that help?
